name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file ./sample-packages/docker/Dockerfile --tag my-image-name:$(date +%s)
    - name: Tag docker image
      run: docker tag my-image-name:$(date +%s) ghcr.io/vishesh/visheshimage:latest
    - name: Log in to the Container registry
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
    - name: Push Image
      run: docker push ghcr.io/VISHESH/image:latest
      
    
